site_name: Cl√©ment Villalard
site_url: https://clementvillalard.com
theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
  logo: assets/owl_athena.png
  favicon: assets/owl_favicon.ico
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  palette:
    # Light Mode
    scheme: default
    primary: blue grey
    accent: teal

plugins:
  - search
  - glightbox

nav:
  - About: index.md
  #- Expertise: expertise.md
  - Portfolio: portfolio.md
  - Deneb Templates:
    - Gallery: Deneb/index.md
    - Basic Histogram: Deneb/histogram.md
    - Small Multiples - Day of the Week: Deneb/smallmultipleday.md
    - Line Chart Brush + Zoom effect: Deneb/linechartbrush.md
    - KPI Card - Area: Deneb/kpi_card_area.md
    - Calendar Heatmap with Histogram: Deneb/calendar_heatmap_histo.md
    - Calendar Heatmap with Histogram - Compact version: Deneb/calendar_heatmap_histo_tiny.md
    - Hourly Heatmap with Histogram: Deneb/hourly_heatmap_histo.md
    - Hourly Heatmap with Bar charts: Deneb/hourly_heatmap_bars.md
    - Shaded line chart with custom tooltip: Deneb/shaded_line_chart_tooltip.md

  #- Themes: themes.md
  - DAX/UDF: DAX.md
  #- Blog


# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences: # This extension is for making diagrams
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: material/linkedin
      link: https://www.linkedin.com/in/clementvillalard
    - icon: material/github
      link: https://github.com/clemviz
    - icon: material/mail
      link: mailto:clement_villalard@outlook.com
  generator: false
copyright: Copyright &copy; 2025 Clement Villalard